FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf --nodocs -y install httpd \
  && microdnf clean all

ADD index.html /var/www/html
ONBUILD ADD src/* /var/www/html

RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf \
  && sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf \
  && chgrp -R 0 /var/log/httpd /var/run/httpd \
  && chmod -R g=u /var/log/httpd /var/run/httpd
  
EXPOSE 8080

USER 1001

CMD httpd -D FOREGROUND
